# Generated by Django 3.2.3 on 2021-05-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_with_ui', '0002_alter_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
